[defaults]
version = "latest"
source = "pypi"
noarch = true
build_args = [] # --noarch will automatically be added if applicable
# The below will only be used if noarch is False
pythons = ["3.8", "3.9", "3.10", "3.11"]
platforms = ["win-64", "osx", "linux"]

### only available on PyPI
[ARC-Alkali-Rydberg-Calculator]
source = "git+https://github.com/nikolasibalic/ARC-Alkali-Rydberg-Calculator/"
noarch = false
build_args = ['--conda-name-differences=oldest-supported-numpy:numpy',
              '--from-wheel'] # build is not PEP-517 compatible, better to stick with pip for now
# BSD3

#[CyRK]
# setup.py needs multiprocessing __main__ protection on windows
# full license txt in recipe breaks the build
#source = "git+https://github.com/jrenaud90/CyRK/"
#noarch = false
#platforms = ["linux"]
# CC BY-SA 4.0

[numbakit-ode]
# BSD

[leveldiagram]
# BSD3

### available via conda-forge
[asteval]
# MIT

[lmfit]
# BSD3

[uncertainties]
# BSD

#[windows-curses]
#source = "git+https://github.com/zephyrproject-rtos/windows-curses/"
#noarch = false
#build_args = ["--from-downloaded-wheel"]
#platforms = ["win-32", "win-64"]
