[defaults]
version = "latest"
source = "pypi"
noarch = true
build_args = [] # --noarch will automatically be added if applicable
# The below will only be used if noarch is False
pythons = ["3.8", "3.9", "3.10", "3.11"]
platforms = ["win-64", "osx-64", "osx-arm64", "linux"]

### only available on PyPI
[ARC-Alkali-Rydberg-Calculator]
source = "git+https://github.com/nikolasibalic/ARC-Alkali-Rydberg-Calculator/"
noarch = false
build_args = ['--conda-name-differences=oldest-supported-numpy:numpy',
              '--from-wheel'] # build is not PEP-517 compatible, better to stick with pip for now
platforms = ["win-64", "osx-64", "linux"]
# BSD3

[CyRK]
source = "git+https://github.com/jrenaud90/CyRK/"
noarch = false
build_args = ["--license=CC-BY-SA", # override so full license text not used
              "--from-wheel"] # non-standard build, rely on pip
# CC BY-SA 4.0

[numbakit-ode]
build_args = ["--from-downloaded-wheel"] # not PEP-517 compatible, don't build locally
# BSD

[leveldiagram]
# BSD3

### available via conda-forge
[asteval]
# MIT

[lmfit]
build_args = ['--license=BSD-3']
# BSD3

[uncertainties]
# BSD
