[defaults]
version = "latest"
source = "pypi"
noarch = true
build_args = [] # --noarch will automatically be added if applicable
# The below will only be used if noarch is False
pythons = ["3.10", "3.11", "3.12", "3.13", "3.14"]
platforms = ["win-64", "osx-arm64", "linux"]

### only available on PyPI
[CyRK]
source = "git+https://github.com/jrenaud90/CyRK/"
noarch = false
build_args = ["--license=CC-BY-SA", # override so full license text not used
              "--from-downloaded-wheel", # non-standard build, use pip wheels
              '--setup-requires="cython>=3.0.0","numpy<2.4",python-gil', # python-gil ensures free-threaded python not grabbed by dependency
              "--ignore-run-exports=python,numpy"] # prevents runtime dependencies being hash locked
              
# CC BY-SA 4.0

[ARC-Alkali-Rydberg-Calculator]
source = "git+https://github.com/nikolasibalic/ARC-Alkali-Rydberg-Calculator/"
noarch = false
build_args = ['--from-downloaded-wheel', # conda-build not working on windows
              "--setup-requires='numpy>=2.0.0',python-gil", # python-gil ensures free-threaded python not grabbed by dependency
              "--ignore-run-exports=python,numpy,libstdcxx"]
# BSD3

[leveldiagram]
# BSD3

### available via conda-forge
[asteval]
# MIT

[lmfit]
build_args = ['--license=BSD-3']
# BSD3

[uncertainties]
# BSD
